Added negative check and is_percentage validator tests
beeware/colosseum pull request #83
Opened 2020-10-15 16:50 UTC by dgmouris

Add a check in the is_percentage validator so that it doesn't allow negative percentages.

This ensures that when the percentage unit is validated, that it can't be negative.

https://github.com/beeware/colosseum/issues/75

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
I'm unsure if this check needs documentation, but guidance on whether or not it does is greatly appreciated.
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2020-10-15 17:06 UTC, dgmouris commented
Hey when I run `tox -e towncrier` I'm getting an Exception of `Can't find your project :(` which I'm a bit confused about.

If someone could help me out a bit on this that would be fantastic, (as well if you do I'll open a PR to help with the contributing docs as this might be a wall for some folks).

Thanks for taking this PR into consideration.

2020-10-18 05:15 UTC, freakboy3742 requested changes
The code looks good (although I'll need to wait to see the tests pass in CI);

The test failure you're currently seeing is because you need to add a *new* file to the changes directory. Essentially you (as the end developer) shouldn't be running `tox -e towncrier`; you only need to run `tox -e towncrier-check`. We (the maintainers) run `towncrier` as part of the release process, which generates the final release notes.

By running town crier yourself, you've deleted an old (unrelated) release note, and CI is noticing that there aren't any release notes.

2020-10-19 01:15 UTC, dgmouris commented
@freakboy3742 Thank you so much for the information on this.

I might add some information to the contributing page to add what I got stuck up on if that's alright:)

2020-10-19 01:18 UTC, dgmouris commented
As minor request. I'm participating in hacktoberfest and I was wondering if you could put hacktoberfest-accepted, totally okay if you don't want to or can't.

I do want to keep on participating project (beeware as whole) as you folks are doing really neat awesome work:)

2020-10-24 00:53 UTC, freakboy3742 approved these changes
Looks good - thanks for the PR!

Unfortunately, we're not going to turn on the Hacktoberfest tag - while we definitely appreciate the contribution, Hacktoberfest is always a magnet for the worst kind of drive-by contributions, which creates a huge burden for us as maintainers. This year it has been especially bad, and the hacktoberfest tag serves as a searchable magnets of these contributions.

2020-10-24 00:53 UTC, merged